### ISSUE TITLE
Management of temporary files

### ISSUE THREAD

**Issue by MNEUW** [openforis/opensarkit#8]
Dear Andreas,

this probably is no issue just a question. 

I just pulled the docker image and started to process S1GRD data using your tutorial on a virtual machine which has a rather small local storage and a mounted drive with a lot of TB's space. Somehow the scripts are producing big amounts of temporary files on my local storage somewhere I cannot not find them. You may know where all the temp-files are stored during processing or you have a hint how I can find them? Need to delete them because I assume processes does not work anymore because my storage was completly filled somehow. 

OS = Debian Ubuntu 18.10
I could not detect any files in /tmp during processing

Best Martin

**Comment by BuddyVolly** [comment]
Dear Martin, 

this is the old, deprecated version of Open SAR Toolkit. Pleas use the new one you can find here: https://github.com/ESA-PhiLab/OpenSarToolkit
There is also a docker image. It i snow python based, and you can select your temp directory throughout the workflow, or directly within a config json file. 

Hope that helps,
Andreas

**Comment by MNEUW** [comment]
Thank you for your reply!!
